name: Backend CI

on:
  push:
    branches:
      - dev1
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: amazon-linux

    services:
      db:
        image: sqlite:3.46.1
        env:

          SQLITE_DB: e_sol
        uses: actions/checkout@v2

      - name: Setup flask.py
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build application
        run: npm run build
